"""Ground-truth labeling for the APT3 emulation dataset.

Authoritative labels come from the OTRF/MITRE APT3 emulation **playbook**
(data/ground_truth/apt3_attack_steps.json, generated by src/build_ground_truth.py
from the published Mordor playbook). An event is 'malicious' if its process +
command matches a documented operator step; we also expose that step's ATT&CK
technique ID.

This replaces the earlier hand-written pattern heuristics, which under-labeled
real attack steps — e.g. `net localgroup Administrators` is documented APT3
Permission Groups Discovery (T1069), but the old patterns called it benign for
lacking `/domain`. Ground truth is now a lookup against the operator's actual
procedure, not our guess.

Honesty note: this is still scoped to the documented emulation. Activity outside
the playbook is treated as benign/ambiguous, same conservative stance as before —
but the malicious set is now authoritative rather than heuristic.
"""
import json
import re
from functools import lru_cache
from pathlib import Path

GT_DIR = Path(__file__).parent.parent / "data" / "ground_truth"
ATTACK_STEPS_FILE = GT_DIR / "apt3_attack_steps.json"


def _norm(s: str) -> str:
    """Lowercase, drop PowerShell-escape backticks and quotes, collapse whitespace."""
    s = (s or "").replace("`", "").replace('"', "").lower()
    return re.sub(r"\s+", " ", s).strip()


def _exe(token: str) -> str:
    """Basename of an executable token, without extension (net.exe -> net)."""
    return token.rsplit("\\", 1)[-1].rsplit("/", 1)[-1].replace(".exe", "")


@lru_cache(maxsize=1)
def _attack_data():
    """Load the playbook: documented OS commands and dropped payload artifacts."""
    if not ATTACK_STEPS_FILE.exists():
        return [], []
    d = json.loads(ATTACK_STEPS_FILE.read_text())
    commands = []
    for s in d.get("commands", []):
        atk = _norm(s["command"])
        first, _, args = atk.partition(" ")
        commands.append((_exe(first), args, s["technique_id"], s["technique_name"]))
    artifacts = [(a["artifact"], a["technique_id"], a["technique_name"])
                 for a in d.get("artifacts", [])]
    return commands, artifacts


def _match(image: str, command_line: str):
    """Return (technique_id, technique_name) for a process event that is part of
    the documented attack, else None. Three signals:
      (1) the process+command matches a documented OS command (shell step),
      (2) the command references a documented payload artifact (vbs/ps1/exe drop),
      (3) it is the Empire C2 agent — encoded PowerShell (in this controlled
          emulation all encoded PowerShell is the Empire launcher, T1086).
    NOTE: much of the attack (the `winenum` module ≈ 12 techniques, keylogger,
    in-agent script execution) runs IN-MEMORY in the agent and spawns no process,
    so it is invisible to process-creation telemetry by construction — a telemetry
    limit, not a labeling gap."""
    exe = _exe(_norm(image).split(" ")[0]) if image else ""
    cmd = _norm(command_line)
    if not (exe or cmd):
        return None
    commands, artifacts = _attack_data()
    for atk_exe, atk_args, tid, tname in commands:
        if atk_exe and atk_exe == exe and atk_args and atk_args in cmd:
            return tid, tname
    for fname, tid, tname in artifacts:
        if fname in cmd:
            return tid, tname
    if exe == "powershell" and "-enc" in cmd:
        return "T1086", "PowerShell"
    return None


def is_malicious_process_creation(image: str, command_line: str) -> bool:
    """True if the process + command matches a documented APT3 operator step."""
    return _match(image, command_line) is not None


def expected_technique(image: str, command_line: str):
    """ATT&CK technique ID of the matched attack step, or None if not an attack."""
    m = _match(image, command_line)
    return m[0] if m else None


# Known benign process images (Windows background activity in this dataset).
KNOWN_BENIGN_IMAGES = frozenset([
    "svchost.exe",
    "explorer.exe",
    "microsoftedgecp.exe",
    "microsoftedge.exe",
    "backgroundtaskhost.exe",
    "taskhostw.exe",
    "dllhost.exe",
    "searchprotocolhost.exe",
    "searchfilterhost.exe",
    "windows.warp.jitservice.exe",
    "runtimebroker.exe",
    "shellexperiencehost.exe",
    "applicationframehost.exe",
    "wuauclt.exe",
    "mscorsvw.exe",
    "vssvc.exe",
    "msiexec.exe",
])


def label_event(event: dict) -> str | None:
    """Return 'malicious', 'benign', or None (skip — not a scorable event).
    Only Sysmon EID 1 (process creation) events are scored."""
    if event.get("log_name", "") != "Microsoft-Windows-Sysmon/Operational":
        return None
    if event.get("event_id") != 1:
        return None

    ed = event.get("event_data", {})
    image = ed.get("Image", "")
    command_line = ed.get("CommandLine", "")

    if is_malicious_process_creation(image, command_line):
        return "malicious"

    img_base = image.split("\\")[-1].lower() if image else ""
    if img_base in KNOWN_BENIGN_IMAGES:
        return "benign"

    # Not clearly malicious or benign — excluded from scoring.
    return None
