"""
Metrics layer: scores the detection layer against ground truth labels.

Detection-layer metrics (computed here):
  - Precision:       TP / (TP + FP)
  - Recall:          TP / (TP + FN)
  - False-positive rate: FP / (FP + TN)  — how much benign noise we generate

Triage-layer metrics are added in step 7.

Honesty notes:
  - Ground truth comes from known attack patterns in the dataset, not from the
    LLM. See src/ground_truth.py for labeling logic.
  - Events that are neither clearly malicious nor clearly benign are excluded
    from scoring rather than guessed at.
  - MTTD is NOT reported — this is static replay data; no time-to-detect exists.
"""

import json
import logging
from pathlib import Path

from src.ground_truth import label_event

log = logging.getLogger(__name__)

DATA_DIR = Path(__file__).parent.parent / "data"
DATASET = DATA_DIR / "empire_apt3_2019-05-14223117.json"
MATCHES_FILE = DATA_DIR / "matches.json"
RESULTS_FILE = Path(__file__).parent.parent / "docs" / "results.md"


def load_events(path: Path) -> list[dict]:
    events = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                events.append(json.loads(line))
    return events


def build_ground_truth(events: list[dict]) -> tuple[set[str], set[str]]:
    """Return (malicious_timestamps, benign_timestamps) for process creation events."""
    malicious, benign = set(), set()
    for e in events:
        label = label_event(e)
        ts = e.get("@timestamp", "")
        ed = e.get("event_data", {})
        # Use timestamp + image as a unique key (timestamp alone can collide)
        key = f"{ts}|{ed.get('Image', '')}"
        if label == "malicious":
            malicious.add(key)
        elif label == "benign":
            benign.add(key)
    return malicious, benign


def score_detection(matches: list[dict], malicious: set[str], benign: set[str]) -> dict:
    """Compute precision, recall, FP rate for the detection layer."""
    matched_keys = {f"{m['timestamp']}|{m['image']}" for m in matches}

    tp = len(matched_keys & malicious)
    fp = len(matched_keys & benign)
    fn = len(malicious - matched_keys)
    tn = len(benign - matched_keys)

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    fp_rate = fp / (fp + tn) if (fp + tn) > 0 else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0

    return {
        "tp": tp,
        "fp": fp,
        "fn": fn,
        "tn": tn,
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "fp_rate": round(fp_rate, 4),
        "f1": round(f1, 4),
        "total_malicious_labeled": len(malicious),
        "total_benign_labeled": len(benign),
        "total_matches": len(matches),
    }


def render_results(detection_metrics: dict) -> str:
    dm = detection_metrics
    return f"""# Detection Results

> Generated by `src/metrics.py` against the OTRF APT3 empire dataset.
> Ground truth: {dm['total_malicious_labeled']} labeled malicious events,
> {dm['total_benign_labeled']} labeled benign events (process creation only).
> Events not clearly malicious or benign are excluded from scoring.

## Detection Layer

| Metric | Value |
|--------|-------|
| True Positives | {dm['tp']} |
| False Positives | {dm['fp']} |
| False Negatives | {dm['fn']} |
| True Negatives | {dm['tn']} |
| **Precision** | **{dm['precision']:.1%}** |
| **Recall** | **{dm['recall']:.1%}** |
| **False-Positive Rate** | **{dm['fp_rate']:.1%}** |
| F1 | {dm['f1']:.3f} |

## Limitations and Honest Caveats

- **Ground truth circularity.** Our rules and ground truth labels are both
  derived from the same observed attack patterns. This produces artificially
  high scores and does NOT demonstrate generalization to unseen attacks. In
  production, ground truth would come from an independent red-team log or
  authoritative SIEM labels.
- **MTTD not reported.** This is static replay data; mean-time-to-detect has no
  meaning without a live event stream.
- **FN scope.** Techniques in the dataset our rules do not cover (e.g. `net use`
  credential spray, `dsregcmd`, lateral movement via `wmic`) are excluded from
  ground truth rather than counted as FNs, because they are ambiguous without
  additional context. The true FN rate against a complete attack taxonomy is
  higher than reported here.
- **FP scope limited.** Only known-benign Windows background processes are in
  the benign set. FP rate against production telemetry with broader process
  diversity would be higher, particularly for the `net.exe` and `cmd.exe` rules.
"""


def main() -> dict:
    if not DATASET.exists():
        raise FileNotFoundError(f"Dataset not found: {DATASET} — run data/fetch.sh first")
    if not MATCHES_FILE.exists():
        raise FileNotFoundError(f"Matches not found: {MATCHES_FILE} — run src/detect.py first")

    events = load_events(DATASET)
    matches = json.loads(MATCHES_FILE.read_text())

    malicious, benign = build_ground_truth(events)
    log.info("Ground truth: %d malicious, %d benign process creation events",
             len(malicious), len(benign))

    detection_metrics = score_detection(matches, malicious, benign)
    log.info("Detection: precision=%.1f%% recall=%.1f%% fp_rate=%.1f%%",
             detection_metrics["precision"] * 100,
             detection_metrics["recall"] * 100,
             detection_metrics["fp_rate"] * 100)

    RESULTS_FILE.parent.mkdir(exist_ok=True)
    RESULTS_FILE.write_text(render_results(detection_metrics))
    log.info("Results written to %s", RESULTS_FILE)

    return detection_metrics


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    main()
